services:
  app_service:
    image: "" #Enter the image name and tag of the image you want to use here

    build:
      context: .
      dockerfile: dockerfile #Replace if your Dockerfile has another name
    hostname: gpu
    domainname: "" #Enter local domain
    entrypoint: /entrypoint_demo.sh
    shm_size: '4gb'
    ports:
      - "host_port:container_port" #Replace host_port & container_port with the actual ports
    networks:
      - app_network
    volumes:
      - app_data:/app/data
    deploy:
      resources:
        limits:
          cpus: "16" # Adjust to your server limits
          memory: "128gb" # Adjust to your server limits
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # Set GPU ID(s)
              capabilities: [gpu]

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  app_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/absolute/path/on/host'  # Set actual host directory
